- name: ping all hosts
  gather_facts: false
  hosts: localhost
  tasks:
    - name: ping a host
      ping:

    - name: Send a message using gotify
      uri:
        url: "http://192.168.1.165/message?token=AMl7hO.nIoxOior"
        method: POST
        body_format: json
        body:
          title: Hello World
          message: "Hello from Ansible via Gotify"
      run_once: true
    

