---
- name: ping all hosts
  gather_facts: false
  hosts: all
  tasks:
    - name: ping a host
      ping:

    - name: Send a message
      ansible.builtin.shell:
        cmd: bash send_telegram.sh "Pings are complete"
        chdir: ~/ansible-setup
      delegate_to: localhost
      run_once: true
    

