- hosts: vm container
  become: true
  become_user: root
  strategy: free
  any_errors_fatal: false
  vars_files:
    - /root/ansible-setup/passwords/secrets.yml
  tasks:

  - name: Starting updates notification
    uri:
      url: "{{ full_gotify_token_ansible }}"
      method: POST
      body_format: json
      body:
        title: Starting update
        message: "Starting updates on all VMs and containers (excluding special hosts)"
    run_once: true

  - name: Update all installed packages (DNF)
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: dnf_update_status
    when: ansible_facts['os_family'] == "RedHat"

  - name: Remove unused packages (DNF)
    dnf:
      autoremove: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Check if reboot is needed (RedHat)
    command: needs-restarting -r
    register: rh_reboot_required
    failed_when: false
    changed_when: false
    when: ansible_facts['os_family'] == "RedHat"

  - name: Update all installed packages (APT)
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status
    when: ansible_facts['os_family'] == "Debian"

  - name: Remove unused packages (APT)
    apt:
      autoremove: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Check if reboot is needed (Debian)
    stat:
      path: /var/run/reboot-required
    register: deb_reboot_required
    when: ansible_facts['os_family'] == "Debian"

  - name: Reboot if needed (RedHat)
    reboot:
      msg: "Reboot required after updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      test_command: uptime
    when:
      - ansible_facts['os_family'] == "RedHat"
      - rh_reboot_required.rc == 1

  - name: Reboot if needed (Debian)
    reboot:
      msg: "Reboot required after updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      test_command: uptime
    when:
      - ansible_facts['os_family'] == "Debian"
      - deb_reboot_required.stat.exists

  - name: Notify updates complete
    uri:
      url: "{{ full_gotify_token_ansible }}"
      method: POST
      body_format: json
      body:
        title: Updates Complete
        message: "Updates complete on all VMs and containers"
    run_once: true
