---
- hosts: speical
  become: true
  become_user: root
  tasks:
  - name: Update all installed packages using dnf module
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: dnf_update_status
    when: ansible_facts['os_family'] == "RedHat"

  - name: Remove dnf packates not needed anymore
    dnf:
      autoremove: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status
    when: ansible_facts['os_family'] == "Debian"

  - name: Remove packages not needed anymore
    apt:
      autoremove: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Check Reboot if necessary
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no


  - name: Reboot if needed
    reboot:
      msg: "Reboot needed do not resist"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      test_command: uptime
    when: reboot_required_file.stat.exists
