- name: Check only the percent disk space used
  gather_facts: yes
  hosts: all
  tasks:
    - name: Get disk usage for root filesystem
      command: df -h /
      register: disk_usage

    - name: Extract percent used from df output
      set_fact:
        percent_used: "{{ disk_usage.stdout_lines[1].split()[4] }}"

    - name: Extract total from df output
      set_fact:
        total_disk: "{{ disk_usage.stdout_lines[1].split()[1]}}"

    - name: Show only the percent used
      debug:
        msg: "HostName: {{ ansible_hostname }} Percent used: {{ percent_used }} Total Space {{ total_disk }}"

    - name: notify of diskspace used at  > 90
      uri:
        url: "http://192.168.1.165/message?token=AMl7hO.nIoxOior"
        method: POST
        body_format: json
        body:
          title: "{{ ansible_hostname }} over 90% usage"
          message: "The device {{ ansible_hostname }} is using {{ percent_used }} of disk space out of {{ total_disk }} you might want to fix that"
      run_once: false
      when: percent_used[:-1] | int > 90
