---
- name: Sync Google Drive to Nextcloud (rclone)
  command: rclone sync gdrive:"Shared_Files" /var/www/nextcloud-data/Sanktem/files/crap/Even\ Worse\ Crap/gdrive

- name: Rescan Nextcloud files for the Sanktem user
  command: sudo -u www-data php /var/www/nextcloud/occ files:scan Sanktem
  args:
    chdir: /var/www/nextcloud
